//! Spawn one configured agent container for a queued run.

use crate::ids::{RunId, SessionId};
use std::path::PathBuf;

use anyhow::{bail, Context, Result};

use crate::runtime::container::{
    ContainerLaunch, ContainerRuntime, ImageDisposition, PtyStream, PTY_STREAM_CAPACITY,
};
use crate::{
    harness::{
        materialize::{
            extensions::ExtensionSet, extensions::ProjectExtensionScope, materialize,
            plugin::PluginHost, report::MaterializationReport, tree::MaterializedTree,
        },
        registry::HarnessDefinition,
    },
    runtime::session::{Run, RunStatus},
    sandbox::{
        credential_proxy::CredentialProxy, egress::EgressTier, image::agent_image_tag,
        image::ToolPin, mounts::agent_mounts, mounts::AGENT_PTY, ports::project_network,
        ports::PortAllocator,
    },
    services::tools::{ProjectToolScope, RoleToolScope},
    store::{audits::StoreAuditSink, Store},
};
use url::Url;

/// Core-owned context for a request received through one run's socket endpoint.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RunContext {
    run_id: RunId,
}

impl RunContext {
    pub fn new(run_id: RunId) -> Self {
        Self { run_id }
    }
}

/// Read boundary for the state that a connected run may observe.
pub trait RunStateStore {
    fn read_run(&self, run_id: RunId) -> Result<Run>;
}

/// Returns the state belonging to the socket's run context, never a caller-selected run.
pub fn own_state(store: &impl RunStateStore, context: RunContext) -> Result<Run> {
    store.read_run(context.run_id)
}

#[cfg(test)]
mod own_state_only {
    use crate::ids::{RunId, SessionId};
    use std::collections::BTreeMap;

    use super::*;

    struct Runs(BTreeMap<RunId, Run>);

    impl RunStateStore for Runs {
        fn read_run(&self, run_id: RunId) -> Result<Run> {
            self.0
                .get(&run_id)
                .cloned()
                .ok_or_else(|| anyhow::anyhow!("run not found"))
        }
    }

    fn run(id: RunId, model: &str) -> Run {
        Run {
            id,
            session_id: SessionId::generate(),
            resolved_model_id: model.into(),
            status: RunStatus::Running,
            events: vec![],
            usage: None,
            exit_code: None,
            cancel_reason: None,
            artifacts: vec![],
            native_session_id: None,
        }
    }

    #[test]
    fn reads_only_the_run_bound_to_the_socket_context() {
        let own_id = RunId::generate();
        let other_id = RunId::generate();
        let own = run(own_id, "own-model");
        let other = run(other_id, "other-model");
        let store = Runs(BTreeMap::from([(own_id, own.clone()), (other_id, other)]));

        assert_eq!(
            own_state(&store, RunContext::new(own_id)).expect("read own run"),
            own
        );
    }
}

/// An inbox notification generated by run supervision rather than by a harness.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InboxItem {
    pub session_id: SessionId,
    pub run_id: RunId,
    pub body: String,
}

/// The small persistence boundary the supervisor needs from the inbox service.
pub trait Inbox {
    fn file(&mut self, item: InboxItem) -> Result<()>;
}

/// A human-owned shell shares the pane plumbing but deliberately has no run identity.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct HumanTerminal {
    pub pty: PtyStream,
}

impl HumanTerminal {
    pub fn open() -> Self {
        Self {
            pty: PtyStream::new(PTY_STREAM_CAPACITY),
        }
    }
}

/// Inputs owned by the caller for one queued run.
pub struct SpawnRequest<'a> {
    pub project_id: &'a str,
    pub harness: &'a HarnessDefinition,
    pub extensions: &'a ExtensionSet,
    pub config_root: PathBuf,
    pub socket_source: PathBuf,
    pub workspace_remote: String,
    /// Agent-visible credential broker endpoint. The credential remains host-only.
    pub credential_proxy: CredentialProxyConfig,
    /// Host-only proxy that injects the sentinel and records the egress authorization.
    pub credential_proxy_authorizer: &'a CredentialProxy,
    /// Durable audit sink for every credential-proxy request made by this run.
    pub audit_store: Store,
    /// Network capability permitted for this run.
    pub egress_tier: EgressTier,
    /// Per-run capability validated by the daemon socket before it routes any agent request.
    pub run_nonce: String,
    pub base_image_digest: String,
    /// The catalog-resolved baseline; project and role scopes can only remove from it.
    pub tools: Vec<ToolPin>,
    pub project_extension_scope: ProjectExtensionScope,
    pub project_tool_scope: ProjectToolScope,
    pub role_tool_scope: RoleToolScope,
    pub plugin: Option<&'a PluginHost>,
}

/// Secret-free endpoint through which an agent can request host-brokered egress.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CredentialProxyConfig {
    endpoint: String,
}

const CREDENTIAL_PROXY_ENDPOINT: &str = "http://host.docker.internal:44000/";

impl CredentialProxyConfig {
    pub fn new(endpoint: impl Into<String>) -> Result<Self> {
        let endpoint = endpoint.into();
        let parsed = Url::parse(&endpoint).context("credential proxy endpoint must be a URL")?;
        if parsed.scheme() != "http"
            || parsed.host_str() != Some("host.docker.internal")
            || parsed.port() != Some(44000)
            || !parsed.username().is_empty()
            || parsed.password().is_some()
            || parsed.path() != "/"
            || parsed.query().is_some()
            || parsed.fragment().is_some()
            || endpoint != CREDENTIAL_PROXY_ENDPOINT
        {
            bail!("credential proxy endpoint must be the host proxy root")
        }
        Ok(Self { endpoint })
    }
}

#[cfg(test)]
#[test]
fn credential_proxy_rejects_credential_bearing_values() {
    assert!(CredentialProxyConfig::new("https://token@example.test").is_err());
}

/// The started container and the materialized configuration used for its prompt prefix.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SpawnedRun {
    pub container: ContainerLaunch,
    pub config: MaterializedTree,
    pub materialization: MaterializationReport,
    pub image: String,
    pub image_disposition: ImageDisposition,
    pub port: u16,
    pub pty_stream: PtyStream,
}

/// Materialize the run configuration, ensure its agent image, then start and attach its PTY.
pub fn spawn(
    run: &mut Run,
    request: SpawnRequest<'_>,
    ports: &PortAllocator,
    runtime: &mut impl ContainerRuntime,
) -> Result<SpawnedRun> {
    let port = ports.allocate()?;
    let run_id = run.id.to_string();
    let proxy = request.credential_proxy_authorizer;
    match spawn_at_port(run, request, port, runtime) {
        Ok(spawned) => Ok(spawned),
        Err(error) => {
            proxy.release_run(&run_id);
            ports.release(port);
            Err(error)
        }
    }
}

fn spawn_at_port(
    run: &mut Run,
    request: SpawnRequest<'_>,
    port: u16,
    runtime: &mut impl ContainerRuntime,
) -> Result<SpawnedRun> {
    if run.status != RunStatus::Queued {
        bail!("only queued runs may be spawned")
    }

    let extensions = request
        .extensions
        .project_scoped(&request.project_extension_scope);
    let (config, materialization) = materialize(
        request.harness,
        &extensions,
        &request.config_root,
        request.plugin,
    )
    .context("materialize run configuration")?;
    config
        .write_to(&request.config_root)
        .context("write run configuration")?;

    if request.run_nonce.trim().is_empty() {
        bail!("run socket capability nonce is required")
    }
    request
        .credential_proxy_authorizer
        .attach_audit_sink(StoreAuditSink::new(request.audit_store)?);
    request
        .credential_proxy_authorizer
        .configure_run(&run.id.to_string(), &request.run_nonce, request.egress_tier)
        .context("configure credential proxy for run")?;
    request
        .credential_proxy_authorizer
        .listen_configured()
        .context("start credential proxy listener")?;

    let tools = request
        .tools
        .into_iter()
        .filter(|tool| {
            request.project_tool_scope.permits(&tool.name)
                && request.role_tool_scope.permits(&tool.name)
        })
        .collect::<Vec<_>>();
    let image = agent_image_tag(&request.base_image_digest, &tools);
    let image_disposition = runtime
        .build_or_reuse_image(&image)
        .context("build or reuse agent image")?;
    let setup = crate::sandbox::workspace::workspace_clone_command(
        &request.workspace_remote,
        &run.id.to_string(),
    )?;
    let mut environment = request
        .credential_proxy_authorizer
        .container_environment_for_run(&run.id.to_string(), &request.run_nonce)
        .into_iter()
        .map(|(key, value)| format!("{key}={value}"))
        .collect::<Vec<_>>();
    environment.push(format!(
        "LOCUS_CREDENTIAL_PROXY={}",
        request.credential_proxy.endpoint
    ));
    environment.push(format!("LOCUS_PORT={port}"));
    let container = ContainerLaunch {
        name: format!("locus-agent-{}", run.id),
        image: image.clone(),
        command: std::iter::once(request.harness.binary.clone())
            .chain(request.harness.launch.argv.iter().cloned())
            .collect(),
        entrypoint: format!(
            "{} && {}",
            crate::sandbox::mounts::entrypoint_setup(),
            setup
        ),
        environment,
        mounts: agent_mounts(
            request.socket_source.display().to_string(),
            request.config_root.display().to_string(),
        )
        .to_vec(),
        network: project_network(request.project_id),
    };
    runtime
        .start_container(&container)
        .context("start agent container")?;
    let pty_stream = PtyStream::new(PTY_STREAM_CAPACITY);
    if let Err(attach_error) = runtime.attach_pty(&container.name, AGENT_PTY, pty_stream.clone()) {
        if let Err(stop_error) = runtime.stop_container(&container.name) {
            return Err(attach_error).context(format!(
                "attach agent PTY; failed to stop partially started container: {stop_error}"
            ));
        }
        return Err(attach_error).context("attach agent PTY");
    }

    run.status = RunStatus::Running;
    Ok(SpawnedRun {
        container,
        config,
        materialization,
        image,
        image_disposition,
        port,
        pty_stream,
    })
}

/// Reserve a run port in Postgres before starting the container. A failed synchronous start
/// releases the durable reservation, while successful runs retain it until terminal cleanup.
pub async fn spawn_persisted(
    store: &Store,
    run: &mut Run,
    request: SpawnRequest<'_>,
    runtime: &mut impl ContainerRuntime,
) -> Result<SpawnedRun> {
    let port = store.allocate_run_port(run.id).await?;
    let run_id = run.id.to_string();
    let proxy = request.credential_proxy_authorizer;
    match spawn_at_port(run, request, port, runtime) {
        Ok(spawned) => Ok(spawned),
        Err(error) => {
            proxy.release_run(&run_id);
            store.release_run_port(run.id).await?;
            Err(error)
        }
    }
}

/// Cancel the container and release its durable port reservation after it reaches a terminal state.
pub async fn cancel_persisted(
    store: &Store,
    proxy: &CredentialProxy,
    run: &mut Run,
    reason: impl AsRef<str>,
    runtime: &mut impl ContainerRuntime,
) -> Result<()> {
    cancel(run, reason, runtime)?;
    proxy.release_run(&run.id.to_string());
    store.release_run_port(run.id).await
}

/// Release a run's resources after any terminal outcome that did not use cancellation.
pub async fn release_terminal_port(
    store: &Store,
    proxy: &CredentialProxy,
    run: &Run,
) -> Result<()> {
    if matches!(
        run.status,
        RunStatus::Queued | RunStatus::Running | RunStatus::Paused
    ) {
        bail!("only terminal runs release durable ports")
    }
    proxy.release_run(&run.id.to_string());
    store.release_run_port(run.id).await
}

/// Stop a running agent container and retain the caller's cancellation reason on its run.
/// Tracks a cooperative pause request. A pause is applied only between turns; the
/// container remains running so its state can be inspected and resumed safely.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PauseController {
    requested: bool,
}

impl PauseController {
    pub fn request(&mut self, run: &Run) -> Result<()> {
        if run.status != RunStatus::Running {
            bail!("only running runs may be paused")
        }
        self.requested = true;
        Ok(())
    }

    /// Returns true when the just-finished turn put the run on hold.
    pub fn after_turn(&mut self, run: &mut Run) -> bool {
        if !self.requested {
            return false;
        }
        self.requested = false;
        run.status = RunStatus::Paused;
        true
    }
}

/// Store the optional identifier the active harness uses for its native conversation.
/// Locus resume remains event-based, so callers may omit this for harnesses without one.
pub fn record_native_session_id(run: &mut Run, native_session_id: impl Into<String>) -> Result<()> {
    let native_session_id = native_session_id.into();
    if native_session_id.trim().is_empty() {
        bail!("native session id must not be empty")
    }
    run.native_session_id = Some(native_session_id);
    Ok(())
}

pub fn cancel(
    run: &mut Run,
    reason: impl AsRef<str>,
    runtime: &mut impl ContainerRuntime,
) -> Result<()> {
    if run.status != RunStatus::Running {
        bail!("only running runs may be cancelled")
    }

    let reason = reason.as_ref();
    if reason.trim().is_empty() {
        bail!("cancellation reason must not be empty")
    }

    runtime
        .stop_container(&format!("locus-agent-{}", run.id))
        .context("stop agent container")?;
    run.status = RunStatus::Cancelled;
    run.cancel_reason = Some(reason.into());
    Ok(())
}

#[cfg(test)]
mod human_terminal_is_not_a_session {
    use super::HumanTerminal;

    #[tokio::test]
    async fn human_shell_has_pty_bytes_but_no_run_or_cost_state() {
        let terminal = HumanTerminal::open();
        let mut ui = terminal.pty.subscribe();

        terminal.pty.write(b"human command output");

        assert_eq!(
            ui.recv().await.expect("terminal bytes"),
            b"human command output"
        );
        // HumanTerminal deliberately contains no Session, Run, Event, or Usage fields.
    }
}

#[cfg(test)]
mod native_session_id {
    use crate::ids::{RunId, SessionId};

    use super::record_native_session_id;
    use crate::runtime::session::{Artifact, Run, RunStatus};

    #[test]
    fn retains_a_harness_session_id_only_on_the_run_that_received_it() {
        let mut run = Run {
            id: RunId::generate(),
            session_id: SessionId::generate(),
            resolved_model_id: "test-model".into(),
            status: RunStatus::Running,
            events: vec![],
            usage: None,
            exit_code: None,
            cancel_reason: None,
            native_session_id: None,
            artifacts: Vec::<Artifact>::new(),
        };

        record_native_session_id(&mut run, "harness-session-42").expect("store harness id");

        assert_eq!(run.native_session_id.as_deref(), Some("harness-session-42"));
    }
}

#[cfg(test)]
mod pause_holds_not_freezes {
    use crate::ids::{RunId, SessionId};

    use super::PauseController;
    use crate::runtime::session::{Artifact, Run, RunStatus};

    fn running_run() -> Run {
        Run {
            id: RunId::generate(),
            session_id: SessionId::generate(),
            resolved_model_id: "test-model".into(),
            status: RunStatus::Running,
            events: vec![],
            usage: None,
            exit_code: None,
            cancel_reason: None,
            native_session_id: None,
            artifacts: Vec::<Artifact>::new(),
        }
    }

    #[test]
    fn pauses_after_the_current_turn_without_stopping_the_container() {
        let mut run = running_run();
        let mut pause = PauseController::default();

        pause.request(&run).expect("request pause");
        assert_eq!(run.status, RunStatus::Running, "the current turn continues");
        assert!(pause.after_turn(&mut run), "next turn is held");
        assert_eq!(run.status, RunStatus::Paused);
    }
}

#[cfg(test)]
mod cancels {
    use crate::ids::{RunId, SessionId};
    use anyhow::Result;

    use super::{cancel, ContainerLaunch, ContainerRuntime, ImageDisposition, PtyStream};
    use crate::{
        runtime::session::{Artifact, Run, RunStatus},
        sandbox::mounts::PtyAttachment,
    };

    #[derive(Default)]
    struct RecordingRuntime {
        stopped: Vec<String>,
    }

    impl ContainerRuntime for RecordingRuntime {
        fn build_or_reuse_image(&mut self, _: &str) -> Result<ImageDisposition> {
            unreachable!("cancel does not build images")
        }

        fn start_container(&mut self, _: &ContainerLaunch) -> Result<()> {
            unreachable!("cancel does not start containers")
        }

        fn attach_pty(&mut self, _: &str, _: PtyAttachment, _: PtyStream) -> Result<()> {
            unreachable!("cancel does not attach PTYs")
        }

        fn stop_container(&mut self, container: &str) -> Result<()> {
            self.stopped.push(container.into());
            Ok(())
        }
    }

    #[test]
    fn stops_a_running_container_and_records_why() {
        let mut run = Run {
            id: RunId::generate(),
            session_id: SessionId::generate(),
            resolved_model_id: "test-model".into(),
            status: RunStatus::Running,
            events: vec![],
            usage: None,
            exit_code: None,
            cancel_reason: None,
            native_session_id: None,
            artifacts: Vec::<Artifact>::new(),
        };
        let mut runtime = RecordingRuntime::default();

        cancel(
            &mut run,
            "superseded by a higher-priority task",
            &mut runtime,
        )
        .expect("running run cancels");

        assert_eq!(run.status, RunStatus::Cancelled);
        assert_eq!(
            run.cancel_reason.as_deref(),
            Some("superseded by a higher-priority task")
        );
        assert_eq!(runtime.stopped, [format!("locus-agent-{}", run.id)]);
    }
}

#[cfg(test)]
mod spawns {
    use std::{
        fs,
        path::{Path, PathBuf},
    };

    use anyhow::{bail, Result};
    use serde_json::json;
    use uuid::Uuid;

    use super::*;
    use crate::{
        harness::{
            materialize::{extensions::ExtensionEntry, extensions::ExtensionSet},
            registry::{load_from_directory, HarnessDefinition},
        },
        runtime::session::{Run, RunStatus},
        sandbox::{
            image::agent_image_tag, image::ToolPin, mounts::Mount, mounts::PtyAttachment,
            mounts::AGENT_PTY, CONFIG_SOURCE,
        },
    };

    #[derive(Default)]
    struct RecordingRuntime {
        calls: Vec<String>,
        started: Option<ContainerLaunch>,
        attached: Option<(String, PtyAttachment)>,
        pty_stream: Option<PtyStream>,
        fail_attach: bool,
    }

    impl ContainerRuntime for RecordingRuntime {
        fn build_or_reuse_image(&mut self, image: &str) -> Result<ImageDisposition> {
            self.calls.push(format!("image:{image}"));
            Ok(ImageDisposition::Built)
        }

        fn start_container(&mut self, container: &ContainerLaunch) -> Result<()> {
            self.calls.push(format!("start:{}", container.name));
            self.started = Some(container.clone());
            Ok(())
        }

        fn attach_pty(
            &mut self,
            container: &str,
            attachment: PtyAttachment,
            stream: PtyStream,
        ) -> Result<()> {
            self.calls.push(format!("pty:{container}"));
            if self.fail_attach {
                bail!("attach fails")
            }
            self.attached = Some((container.into(), attachment));
            self.pty_stream = Some(stream);
            Ok(())
        }

        fn stop_container(&mut self, container: &str) -> Result<()> {
            self.calls.push(format!("stop:{container}"));
            Ok(())
        }
    }

    fn root() -> PathBuf {
        std::env::temp_dir().join(format!("locus-run-spawns-{}", Uuid::new_v4()))
    }

    fn spawn_request<'a>(
        harness: &'a HarnessDefinition,
        extensions: &'a ExtensionSet,
        config_root: PathBuf,
        credential_proxy_authorizer: &'a CredentialProxy,
    ) -> SpawnRequest<'a> {
        SpawnRequest {
            project_id: "project-1",
            harness,
            extensions,
            config_root,
            socket_source: PathBuf::from("/tmp/locus.sock"),
            workspace_remote: "/var/lib/locus/repos/project.git".into(),
            credential_proxy: CredentialProxyConfig::new(CREDENTIAL_PROXY_ENDPOINT).unwrap(),
            credential_proxy_authorizer,
            audit_store: Store::connect_lazy("postgres://locus@127.0.0.1/locus").unwrap(),
            egress_tier: EgressTier::Model,
            run_nonce: "nonce".into(),
            base_image_digest: "sha256:base".into(),
            tools: vec![
                ToolPin {
                    name: "git".into(),
                    version: "2.49".into(),
                },
                ToolPin {
                    name: "rg".into(),
                    version: "14".into(),
                },
                ToolPin {
                    name: "sqlx".into(),
                    version: "0.8".into(),
                },
            ],
            project_extension_scope: {
                let mut scope = ProjectExtensionScope::default();
                scope.disable_extension("rules");
                scope
            },
            project_tool_scope: ProjectToolScope::new(["sqlx"]),
            role_tool_scope: RoleToolScope::new(["git"]),
            plugin: None,
        }
    }

    #[tokio::test]
    async fn persisted_spawn_uses_the_reserved_port() {
        let registry =
            load_from_directory(Path::new(env!("CARGO_MANIFEST_DIR")).join("../../harnesses"))
                .expect("registry loads");
        let mut extensions = ExtensionSet::default();
        extensions.insert(
            "context",
            vec![ExtensionEntry::new("base.md", json!({}), "base context")],
        );
        extensions.insert(
            "rules",
            vec![ExtensionEntry::new(
                "no-secrets.md",
                json!({}),
                "never commit secrets",
            )],
        );
        let config_root = root();
        let run_id = RunId::generate();
        let mut run = Run {
            id: run_id,
            session_id: SessionId::generate(),
            resolved_model_id: "test-model".into(),
            status: RunStatus::Queued,
            events: vec![],
            usage: None,
            exit_code: None,
            cancel_reason: None,
            native_session_id: None,
            artifacts: vec![],
        };
        let credential_proxy_authorizer = CredentialProxy::new("test-secret", "api_key");
        let request = spawn_request(
            registry.by_name("claude").expect("claude harness"),
            &extensions,
            config_root.clone(),
            &credential_proxy_authorizer,
        );
        let mut runtime = RecordingRuntime::default();

        let _fixed_port = crate::testkit::postgres::serialize_fixed_port();

        let spawned = spawn_at_port(&mut run, request, 43_210, &mut runtime)
            .expect("run spawns with its durable reservation");

        let image = agent_image_tag(
            "sha256:base",
            &[ToolPin {
                name: "rg".into(),
                version: "14".into(),
            }],
        );
        assert_eq!(run.status, RunStatus::Running);
        assert_eq!(spawned.image, image);
        assert!(spawned.config.file("CLAUDE.md").is_some());
        assert!(spawned.config.file("rules/no-secrets.md").is_none());
        assert_eq!(
            fs::read_to_string(config_root.join("CLAUDE.md")).unwrap(),
            "base context"
        );
        assert_eq!(
            runtime.calls,
            [
                format!("image:{image}"),
                format!("start:locus-agent-{run_id}"),
                format!("pty:locus-agent-{run_id}")
            ]
        );
        assert_eq!(spawned.image_disposition, ImageDisposition::Built);
        assert_eq!(spawned.port, 43_210);
        assert_eq!(spawned.container.mounts[1].destination, CONFIG_SOURCE);
        assert_eq!(
            spawned.container.mounts,
            vec![
                Mount {
                    source: "/tmp/locus.sock".into(),
                    destination: "/run/locus.sock".into(),
                    read_only: false
                },
                Mount {
                    source: config_root.display().to_string(),
                    destination: CONFIG_SOURCE.into(),
                    read_only: true
                }
            ]
        );
        assert_eq!(spawned.container.network, "locus-project-1");
        assert!(spawned
            .container
            .environment
            .iter()
            .any(|value| value == &format!("LOCUS_PORT={}", spawned.port)));
        assert!(spawned
            .container
            .environment
            .iter()
            .any(|value| value == "LOCUS_RUN_NONCE=nonce"));
        assert!(spawned
            .container
            .environment
            .iter()
            .any(|value| value == &format!("LOCUS_RUN_ID={run_id}")));
        assert_eq!(
            credential_proxy_authorizer
                .listener_address()
                .unwrap()
                .port(),
            44_000
        );
        assert!(spawned
            .container
            .environment
            .iter()
            .any(|value| value == "ANTHROPIC_API_KEY=sk-locus-sentinel"));
        assert!(spawned
            .container
            .environment
            .iter()
            .any(|value| value == "LOCUS_CREDENTIAL_PROXY=http://host.docker.internal:44000/"));
        assert!(!spawned
            .container
            .environment
            .iter()
            .any(|value| value.contains("test-secret")));
        assert!(credential_proxy_authorizer.audit_rows().is_empty());
        assert_eq!(
            runtime.attached,
            Some((spawned.container.name.clone(), AGENT_PTY))
        );
        let mut ui = spawned.pty_stream.subscribe();
        assert_eq!(
            runtime
                .pty_stream
                .as_ref()
                .expect("runtime received PTY stream")
                .write(b"agent output"),
            1
        );
        assert_eq!(
            ui.try_recv().expect("UI receives PTY bytes"),
            b"agent output"
        );

        let _ = fs::remove_dir_all(config_root);
    }

    #[tokio::test]
    async fn stops_the_container_when_pty_attachment_fails() {
        let registry =
            load_from_directory(Path::new(env!("CARGO_MANIFEST_DIR")).join("../../harnesses"))
                .expect("registry loads");
        let mut extensions = ExtensionSet::default();
        extensions.insert(
            "context",
            vec![ExtensionEntry::new("base.md", json!({}), "base context")],
        );
        let config_root = root();
        let run_id = RunId::generate();
        let mut run = Run {
            id: run_id,
            session_id: SessionId::generate(),
            resolved_model_id: "test-model".into(),
            status: RunStatus::Queued,
            events: vec![],
            usage: None,
            exit_code: None,
            cancel_reason: None,
            native_session_id: None,
            artifacts: vec![],
        };
        let credential_proxy_authorizer = CredentialProxy::new("test-secret", "api_key");
        let request = spawn_request(
            registry.by_name("claude").expect("claude harness"),
            &extensions,
            config_root.clone(),
            &credential_proxy_authorizer,
        );
        let mut runtime = RecordingRuntime {
            fail_attach: true,
            ..Default::default()
        };

        let _fixed_port = crate::testkit::postgres::serialize_fixed_port();
        let error = spawn_at_port(&mut run, request, 43_210, &mut runtime)
            .expect_err("failed attachment rolls back the container");

        assert!(error.to_string().contains("attach agent PTY"));
        assert_eq!(run.status, RunStatus::Queued);
        let image = agent_image_tag(
            "sha256:base",
            &[ToolPin {
                name: "rg".into(),
                version: "14".into(),
            }],
        );
        assert_eq!(
            runtime.calls,
            [
                format!("image:{image}"),
                format!("start:locus-agent-{run_id}"),
                format!("pty:locus-agent-{run_id}"),
                format!("stop:locus-agent-{run_id}"),
            ]
        );
        let _ = fs::remove_dir_all(config_root);
    }
}
